### ISSUE TITLE
Is swap memory development testing not supported?

### ISSUE THREAD

**Issue by foxxcn** [fleek-network/lightning#19]
I am using Ubuntu 22.04 LTS, and I encountered issues with swap memory support during development and testing. Despite attempting to increase the swap memory size due to my hardware limitations with only 8GB of RAM, the problem persists. The system hangs while attempting to complete the **_Lightning CLI (bin)_** build, accompanied by intense fan activity, ultimately leading to a freeze.
**Tip**
_I hope to make it easier for developers to test and demonstrate on computers with small memory. 24G is more difficult for ordinary laptops._

**Comment by matthias-wright** [comment]
Hi @foxxcn, thank you for reaching out.
A minimum of 32 GB RAM is required to run a node, see our docs for more deteils: https://docs.fleek.network/docs/node/requirements/
As for development, I remember developing on a machine with 16 GB RAM. I was experiencing occasional freezes, but it worked okay for the most part.
We do recommend 32GB RAM for development as well.
